language: ruby
sudo: false
cache: bundler

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby

gemfile:
  - Gemfile
  - gemfiles/rack_v1.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
  exclude:
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.0
      gemfile: Gemfile
    - rvm: 2.1
      gemfile: Gemfile
